### ISSUE TITLE
[BUG] Receiving Tune Request (0xF6) via USB MIDI 1.0 device doesn't work.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#236]
**Describe the bug**
Tune Request (System Common)  messages could not be received via USB MIDI 1.0 device which work with an existing USB MIDI 1.0 driver (USBAUDIO.sys).

**To Reproduce**
1. Set the Roland UM-ONE to class compliant mode and short UM-ONE's INPUT and OUTPUT to loop back the message. 
2. Attach UM-ONE to the PC and make sure the device is working with USBAUDIO.sys.
3. Open midi.exe in two windows.
4. From one, monitor UM-ONE.
5. From the other, run following command with attached file:
'midi endpoint send-message 0x10F60000 --count 10'

**Expected behavior**
Sent Tune Request messages is received.

**Observed behavior**
No Tune Request messages is received.

**Screenshots**
All messages are sent and received on the USB transaction.

![image](https://github.com/microsoft/MIDI/assets/114042371/6d63ef8f-3c87-4bb6-9b7b-5bfe0f26337d)

**Installer Name or Version**
- DP4 Daily3 (Windows.MIDI.Services.Developer.Preview.4.x64.1.0.24018.1850.exe)

**Desktop (please complete the following information):**
- OS: Windows 11 23H2 build 26020.1000

**Device information, if this is with an external MIDI device:**
- Roland UM-ONE mk2
- Classic MIDI 1.0 class driver (USBAUDIO.sys)

**Application Information**
- midi.exe console app.

**Additional context**
If the device is working with the new USB MIDI 2.0 driver (USBMidi2.sys), it works fine.

**Comment by Psychlist1972** [comment]
Thank you again for your report @m-komo

**Comment by Psychlist1972** [comment]
This should be fixed as soon as we pull in the new AM Lib from Andrew. We're working on the vcxpkg approach to be able to properly consume that.

**Comment by m-komo** [comment]
The issue persists on the DP5.
- MIDI Service version: DP5 (1.0.24066.2126)
- Driver version: DP5 (10.0.14)
- OS version: Windows 11 24H2 build 26063.1

**Comment by MusicMaker** [comment]
Tested with DP6 0x10F60000 onP device with UMP and legacy MIDI1 support. using windows legacy driver, device goes in legacy mode and when sending this UMP package a legacy MIDI F6 was received on the device.

**Comment by m-komo** [comment]
I confirmed that the issue has been solved.

- Service: Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe
- Driver: [interim preview build] 240713-USBMidi2-x86-TESTSIGNED.zip (DriverVer = 07/13/2024,23.1.50.504)
