### ISSUE TITLE
[BUG] MIDI Service gets stuck.

### ISSUE THREAD

**Issue by m-komo** [microsoft/MIDI#245]
**Describe the bug**
If I send an undefined system common message, such as 0xF4 or 0xF5, MIDI Service seems to get stuck.
If this happens, MidiSrv cannot be stop/restart and restarting OS is required.

- This issue only occurs if the USB MIDI 1.0 device is running with the USB MIDI 2.0 driver (USBMidi2.sys).

- If the USB MIDI 1.0 device is running with the USB MIDI 1.0 driver (USBAUDIO.sys) or if the USB MIDI 2.0 device is running with the USB MIDI 2.0 driver (USBMidi2.sys), this issue never happens.

**To Reproduce**
1. Set the Roland UM-ONE mk2 to class-compliant mode and short INPUPT and OUTPUT to loop back messages.
2. Attach the UM-ONE to PC.
3. Open the Device Manager and load the USB MIDI 2.0 driver (USBMidi2.sys) manually against the attached UM-ONE.
4. Open midi.exe in two windows.
5. From one, monitor UM-ONE.
6. From the other, run following command:
'midi endpoint send-message 0x10F40000'
7. On the monitor window, press escape to stop monitoring.

Monitoring cannot be terminated.
If I run another send-message command, it seems to be stuck.
And finally, it is necessary to restart OS to recover.

**Expected behavior**
MIDI Service and midi console continue to work.

**Installer Name or Version**
Windows.MIDI.Services.Developer.Preview.4.x64.1.0.24022.2031.exe

**Desktop (please complete the following information):**
- OS: Windows 11 23H2 build 26040.1000

**Device information, if this is with an external MIDI device:**
- Roland UM-ONE mk2
- USB MIDI 2.0 class driver (USBMidi2.sys)

**Application Information**
- midi.exe console app.

**Comment by Psychlist1972** [comment]
Thank you @m-komo 

@AmeNote-Michael this may be related to the other translation bugs you were seeing in the driver.

**Comment by m-komo** [comment]
The issue persists on the DP5.
- MIDI Service version: DP5 (1.0.24066.2126)
- Driver version: DP5 (10.0.14)
- OS version: Windows 11 24H2 build 26063.1

**Comment by m-komo** [comment]
This issue is caused by all of the following undefined system common/realtime messages (not only by 0xF4 and 0xF5).

- 0xF4 (0x10F40000)
- 0xF5 (0x10F50000)
- 0xF9 (0x10F90000)
- 0xFD (0x10FD0000)

**Comment by AmeNote-Michael** [comment]
This could be a logic error in handling undefined messages. Shall investigate for next attestation signed driver. Thank you for input.

**Comment by AmeNote-Michael** [comment]
Should just pass the message along as a system common / realtime and not drop message.

**Comment by AmeNote-Michael** [comment]
This issue is resolved in latest USB MIDI 2.0 driver which now properly handles System Common and Real Time messages which in some cases would get caught in an endless loop.

**Comment by AmeNote-Michael** [comment]
@sat-okada discovered that case 0xfd still not being handled in latest test signed driver.

**Comment by AmeNote-Michael** [comment]
This issue is resolved and can be closed with driver release.

**Comment by Sho-KDM** [comment]
We tested with new driver(10.0.1.5). However, this issue is still existing when we send 0xFD (0x10FD0000). In that case, we need to force reboot OS for recovering. 

Installer Name or Version
- Windows.MIDI.Services.In-Box.Service.-.Developer.Preview.6.1.0.24194.2233-x64.exe

Desktop (please complete the following information):
- OS: Windows 11 24H2 build 26100.1586

Device information, if this is with an external MIDI device:
- Roland UM-ONE mk2
- Driver: driver-august-2024-fixed(USBMIDI2_10.0.1.5_x64.zip)

Application Information
- midi.exe console app.

**Comment by AmeNote-Michael** [comment]
@Sho-KDM thank you for the update - can you please create a new issue specific to the case for 0xfd. Looking into code, somehow update for the writing to USB missed this case. As this is a closed issue, would like to have a new issue opened to resolve. I am currently checking the fix.

**Comment by Sho-KDM** [comment]
@AmeNote-Michael I cretaed new issue #397. Could you check that?

@m-komo If there is something missing thing, could you add that as comment?
