### ISSUE TITLE
[BUG] Legacy Sysex from MIDI USB device results in F0/F7 in UMP data

### ISSUE THREAD

**Issue by MusicMaker** [microsoft/MIDI#374]
**Describe the bug**
UMP sysex data in midi.exe shows F0 and F7 inside UMP packets. Per UMP specification F0 and F7 these should be  used as start and end of system exclusive message indicators. (In Sysex8 these are treated as data)

**To Reproduce**
1. Connect a MIDI  USB device with legacy MIDI descriptor.
2. Install Windows Midi 2.0 driver  for the device
3. Install Developer preview 6
4.  midi.exe service stop and then start 
5.  midi ep monitor
6. Observe sysex contains F0 and F7 in UMP data

**Expected behavior**
No F0 and F7 in UMP data

**Screenshots**
![Screenshot from 2024-07-26 12-19-54](https://github.com/user-attachments/assets/c67d253f-4d61-4cf2-b23b-ef4da070aa0a)

**Installer Name or Version**
Windows MIDI 2.0 DP6 with DP2 driver (latest)

**Desktop (please complete the following information):**
Windows 11 Canary

**Device information, if this is with an external MIDI device:**
DIY MIDI Device using MCU

**Application Information**
Own firmware

**Additional context**
ALSA handles this correctly.

**Comment by AmeNote-Michael** [comment]
@MusicMaker how are you generating the SYSEX data. Routines only look and parse out F0 and F7 at the start and end of SYSEX as indicated by CIN in USB MIDI 1.0. If there are further embedded F0 and F7 in the stream, then system will pass along.

**Comment by AmeNote-Michael** [comment]
@MusicMaker This was resolved in latest driver - if you are using older driver version like in issue 375, then your output is expected. Again, this has been resolved - please confirm, are you using latest test signed driver?

**Comment by MusicMaker** [comment]
Using the latest (public) one from github, DP2 right? BTW I insert these real time data in Sysex messages on the device. For I create a legacy (DIN) byte stream and then convert it to USB packets (DYI MCU). I think this case was it was in USB legacy mode then sending it over USB to Windows.

**Comment by Psychlist1972** [comment]
Closing as fixed in the August 2024 driver release. If you find it not to be when testing, will reopen.

**Comment by MusicMaker** [comment]
Regressed with DP6, confirmed this is fixed.

**Comment by Psychlist1972** [comment]
> Regressed with DP6, confirmed this is fixed.

I assume you're not using the correct word here due to language. "Regressed" would mean that the problem is not fixed and has come back.

**Comment by MusicMaker** [comment]
fixed : changed resgressed to regression tested
